### ISSUE TITLE
typos in wiki describing equations files

### ISSUE THREAD

**Issue by rhaas80** [BenMql/coral#13]
In Input_file_equations the wiki refers to a file `LP_user_sources_definition.f90` which is incorrect since the file is named `LP_user_sources_definitions.f90` with an `s`.

The `>>EOF<<` marker is only mentioned in the Pittfalls section.

There's also some (English language typos) and an inconsistency in that the directory called `coral` in that file is designated using the `$CORAL_ROOT` variable in other places.

**Comment by BenMql** [comment]
Roland, 

Directories and filenames are now consistent. The `>>EOF<<` marker is now mentionned earlier. 
 
I realise by reading this wiki page that I need to organise the information a little differently so that it's streamlined and gradual. I'm working on putting in better perpective the tutorial notebooks, the benchmarks documentation, and the `Input_file_equations` page of the wiki.
