### ISSUE TITLE
Variable length (src/layer_pencils/LP_text_parsing.f90 at line 25) is not yet allocated

### ISSUE THREAD

**Issue by acellison** [BenMql/coral#24]
Crash when starting up a coral run due to unallocated variable 'length'.  forrtl gives the following error message:
`forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable LENGTH when it is not allocated`

**Comment by acellison** [comment]
This occurs when compiling with the flags `MPIFLAGS=-check\ all\ -stand\ f03\ -traceback` using the following modules:
intel/17.4 impi/17.3 mkl/17.3 fftw/3.3.4

**Comment by BenMql** [comment]
Coral calls a C function `parse_text` to read the text files. It does so twice: the first call merely counts the number of lines so that arrays `arr_of_lines` and `length` can be allocated appropriately. These arrays unused during the first call, and then they are filled during the second call. 

Even when unused by the function call, it apparently sometimes cause trouble to use `C_loc(length)` as an argument when `length` is not yet allocated.

This is now solved: `length` is first allocated with size 1, `parse_text` is called a first time, then `length` is deallocated and reallocated with the proper size (and the rest of the code is unchanged).
