### ISSUE TITLE
Restarting from checkpoint overwrites output

### ISSUE THREAD

**Issue by acellison** [BenMql/coral#25]
The time index resets to zero when restarting a run.  This means filenames generated using the time index will match those from previous runs, despite the simulation being further along in nondimensional time.  This causes saved profiles, slices, volumes, etc. to be overwritten with the latest results.

**Comment by BenMql** [comment]
Abe, 
That's a good suggestion, which has been formulated several time. I implemented it.
Starting at v1.2.2, Coral records the timestep integer in `CheckPoints/dt.sav`. 
If the folder when Coral runs has some existing timeseries and `dt.sav` contains the timestep integer, then Coral resumes the previous run without overwriting data.
(More precisely, the existence of timeseries is assessed by searching for the file `Timeseries/time.dat`.)
If one of the conditions is missing (because the checkpoint was generated with an old version, or the `Timeseries/time.dat` file is missing), then Coral falls back to the old behaviour (i.e. starts from timestep 1 and overwrites files).

**Comment by acellison** [comment]
When creating initial data for the new timeseries format, how should the ./Restart/dt.sav be formatted?  My impression is it should be a binary file consisting of [dt, absolute_time, i_timestep], where dt is the initial timestep (double precision), absolute time is zero (double precision) and i_timestep is one (32-bit integer).  Are these data types/sizes correct?

EDIT: Just checked the integer format - it requires a 64-bit integer, so all data types are 8 bytes.

**Comment by BenMql** [comment]
Your first intuition was correct.
`dt.sav` has to be either a 16 bytes file composed of two 8-bytes float (in which case Coral starts from timestep 1); or a 20 bytes file with a 4-byte integer (`np.in32` if you manufacture the file with python) at the end. 

Versions of the code newer than commit f5e6b0a` can be restarted with an old Checkpoint in a new folder, and will generate automatically a `dt.sav` file that allows for restarting in the same folder subsequently.
